name: quality gates
on: push
jobs:
  quality-gates:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
      - name: Install dependencies
        run: npm ci
      - name: Check types
        run: npm run type-check
      - name: Run prettier
        run: npm run format:check
      - name: Check linting
        run: npm run lint
      - name: Add user before deploy
        run: git config --global user.email "a.n.bochkarev1991@gmail.com" && git config --global user.name "anbochkarev1991"
      - name: Deploy to gh-pages branch
        run: npm run deploy