name: quality gates
on: push
jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v3
      - name: Install dependencies
        run: npm i
      - name: Run prettier
        run: npx prettier --check "{**/*,*}.{js,ts,jsx,tsx,vue,astro,css}"
